import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Activity,Users,Trophy,Clock3,CalendarDays,TrendingUp,Sparkles,Upload,Search,ChevronRight,Flame,MoreHorizontal,CheckCircle2,Target,Timer,Medal,X,Menu,ArrowUpRight,FileJson,RefreshCw,AlertCircle,LockKeyhole,Eye,EyeOff,Swords}from'lucide-react';
import'./style.css';

const labels={strength_training:'Musculação',circuit_training:'Circuito',functional_training:'Funcional',cross_training:'Cross training',spinning:'Spinning',running:'Corrida',walking:'Caminhada',cycling:'Ciclismo'};
const challenge={name:'Desafio 7 semanas',start:'2026-08-24',end:'2026-10-11',days:49,target:42,min:30};
const IMPORT_PASSWORD='Triprimata';
const nav=[['dashboard','Visão geral',Activity],['ranking','Ranking',Trophy],['duels','Duelos',Swords],['participants','Participantes',Users],['evolution','Evolução',TrendingUp],['calendar','Calendário',CalendarDays],['curiosities','Curiosidades',Sparkles],['import','Importar dados',Upload]];

function normalize(raw){
 if(!raw||typeof raw!=='object')throw Error('O arquivo não contém um objeto JSON válido.');
 // Aceita tanto o export original quanto versões embrulhadas em data/challenge.
 const source=raw.data&&typeof raw.data==='object'&&!Array.isArray(raw.data)?raw.data:raw;
 const members=Array.isArray(source.members)?source.members:[];
 const map=Object.fromEntries(members.map(m=>[m.id,m]));
 const checkins=Array.isArray(source.check_ins)?source.check_ins:(Array.isArray(source.checkIns)?source.checkIns:[]);
 if(!members.length&&!checkins.length)throw Error('JSON reconhecido, mas não encontrei members e check_ins.');
 const activities=checkins.map(c=>{
   const nested=(c.check_in_activities||[]).map(x=>x?.platform_activity).filter(Boolean);
   const type=c.activity_type||nested[0]||'';
   const rawDuration=c.duration_millis!=null?Number(c.duration_millis)/60000:Number(c.duration)||0;
   const calories=c.calories!=null?Number(c.calories):null;
   const steps=c.steps!=null?Number(c.steps):null;
   const parsedDistance=c.distance_miles!=null?Number(String(c.distance_miles).replace(',','.')):null;
   // O export pode conter valores claramente corrompidos (ex.: centenas de milhas em um único check-in).
   const distanceMiles=Number.isFinite(parsedDistance)&&parsedDistance>=0&&parsedDistance<=50?parsedDistance:null;
   return{id:c.id,participantId:c.account_id,name:map[c.account_id]?.full_name||'Não informado',avatar:map[c.account_id]?.profile_picture_url,date:c.occurred_at||c.created_at,minutes:Math.max(0,rawDuration),calories:Number.isFinite(calories)?calories:null,steps:Number.isFinite(steps)?steps:null,distanceMiles:distanceMiles,type:labels[type]||type||'Não informado',valid:rawDuration>=challenge.min,raw:c};
 });
 return{members,activities,meta:source};
}
const fmt=m=>{m=Number(m)||0;const h=Math.floor(m/60),x=Math.round(m%60);return h?`${h}h ${x}min`:`${x}min`};
const dateObj=d=>d?new Date(d):null;
const day=d=>d?dateObj(d).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—';
const shortDay=d=>d?dateObj(d).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',timeZone:'America/Sao_Paulo'}):'—';
function streak(a){const ds=[...new Set(a.map(x=>day(x.date)))].map(x=>{const [d,m,y]=x.split('/').map(Number);return new Date(y,m-1,d)}).sort((a,b)=>a-b);let best=0,cur=0;ds.forEach((d,i)=>{cur=i&&d-ds[i-1]===86400000?cur+1:1;best=Math.max(best,cur)});return best}
const pct=(v,max)=>Math.min(100,Math.round((v/(max||1))*100));
const isoDay=d=>d.toISOString().slice(0,10);

function App(){
 const[page,setPage]=useState('dashboard'),[sel,setSel]=useState(null),[q,setQ]=useState(''),[state,setState]=useState(null),[mobile,setMobile]=useState(false),[notice,setNotice]=useState(''),[noticeType,setNoticeType]=useState('ok'),[importUnlocked,setImportUnlocked]=useState(false),[showPassword,setShowPassword]=useState(false),[password,setPassword]=useState(''),[passwordError,setPasswordError]=useState('');
 const fileInputRef=useRef(null);
 const loadDefault=()=>fetch('/challenge-data.json').then(r=>{if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}).then(x=>setState(normalize(x))).catch(e=>setState({members:[],activities:[],error:e.message}));
 useEffect(()=>{loadDefault()},[]);
 const members=state?.members||[],activities=state?.activities||[];
 const stats=useMemo(()=>members.map(m=>{const a=activities.filter(x=>x.participantId===m.id),v=a.filter(x=>x.valid);return{m,a,v,time:v.reduce((s,x)=>s+x.minutes,0),days:new Set(v.map(x=>day(x.date))).size,streak:streak(v),avg:v.length?v.reduce((s,x)=>s+x.minutes,0)/v.length:0,calories:v.reduce((s,x)=>s+(x.calories||0),0),steps:v.reduce((s,x)=>s+(x.steps||0),0),distance:v.reduce((s,x)=>s+(x.distanceMiles||0),0)}}).sort((a,b)=>b.v.length-a.v.length||b.time-a.time).map((s,i)=>({...s,rank:i+1})),[members,activities]);
 const filtered=stats.filter(s=>(s.m.full_name||'').toLowerCase().includes(q.toLowerCase()));
 const valid=activities.filter(x=>x.valid),total=valid.reduce((s,x)=>s+x.minutes,0),collectiveTarget=members.length*challenge.target,completion=pct(valid.length,collectiveTarget);
 const requestImportAccess=()=>{setPassword('');setPasswordError('');setShowPassword(true)};
 const openFilePicker=()=>fileInputRef.current?.click();
 const unlockImport=()=>{if(password===IMPORT_PASSWORD){setImportUnlocked(true);setShowPassword(false);setPassword('');setPasswordError('');setTimeout(openFilePicker,120)}else setPasswordError('Senha incorreta. Apenas usuários autorizados podem importar dados.')};
 const importJSON=e=>{if(!importUnlocked){requestImportAccess();e.target.value='';return}const f=e.target.files?.[0];if(!f)return;setNotice('Importando e validando o arquivo…');setNoticeType('info');const r=new FileReader();r.onload=()=>{try{const text=String(r.result||'').replace(/^\uFEFF/,'').trim();const parsed=JSON.parse(text);const normalized=normalize(parsed);setState(normalized);setSel(null);setPage('dashboard');setNotice(`Dados importados: ${normalized.members.length} participantes e ${normalized.activities.length} check-ins.`);setNoticeType('ok');}catch(err){setNotice(`Falha na importação: ${err.message}`);setNoticeType('error');}};r.onerror=()=>{setNotice('Não foi possível ler o arquivo.');setNoticeType('error')};r.readAsText(f);e.target.value=''};
 const navigate=p=>{setPage(p);if(p!=='participants')setSel(null);setMobile(false)};
 if(!state)return <div className="splash"><div className="splash-logo">🐀</div><h1>GYM RATS <span>ANALYTICS</span></h1><div className="loader"/><p>Preparando seu painel de performance…</p></div>;
 if(state.error)return <div className="splash"><div className="error-icon">!</div><h2>Não foi possível carregar os dados</h2><p>{state.error}</p><label className="primary"><Upload size={16}/> Importar JSON<input type="file" accept="application/json,.json" onChange={importJSON}/></label></div>;
 return <div className="app"><aside className={mobile?'open':''}><div className="brand"><div className="brandmark">🐀</div><div><b>GYM RATS</b><span>ANALYTICS</span></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div><div className="challenge-card"><div className="live"><i/> DESAFIO ATIVO</div><strong>{challenge.name}</strong><span>24 AGO — 11 OUT 2026</span><div className="mini-progress"><i style={{width:`${completion}%`}}/></div><small>{valid.length} válidos de {members.length*challenge.target} possíveis</small></div><nav>{nav.map(([id,n,I])=><button key={id} className={page===id?'active':''} onClick={()=>navigate(id)}><I size={17}/><span>{n}</span>{id==='ranking'&&<em>TOP</em>}</button>)}</nav><div className="sidebar-bottom"><label className="import"><Upload size={16}/> Importar dados<input type="file" accept="application/json,.json" onChange={importJSON}/></label><div className="data-status"><CheckCircle2 size={15}/><span>{activities.length} registros carregados</span></div></div></aside><nav className="mobile-bottom-nav" aria-label="Navegação móvel"><button className={page==='dashboard'?'active':''} onClick={()=>navigate('dashboard')}><Activity size={19}/><span>Início</span></button><button className={page==='ranking'?'active':''} onClick={()=>navigate('ranking')}><Trophy size={19}/><span>Ranking</span></button><button className={page==='duels'?'active':''} onClick={()=>navigate('duels')}><Swords size={19}/><span>Duelos</span></button><button className={page==='evolution'?'active':''} onClick={()=>navigate('evolution')}><TrendingUp size={19}/><span>Evolução</span></button><button className="more-nav" onClick={()=>setMobile(true)}><MoreHorizontal size={19}/><span>Mais</span></button></nav>
 <main><header><div className="title"><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div><span className="eyebrow">PERFORMANCE CENTER / {page==='dashboard'?'OVERVIEW':page.toUpperCase()}</span><h1>{page==='dashboard'?'Visão geral':nav.find(n=>n[0]===page)?.[1]||'GYM RATS'}</h1></div></div><div className="header-actions"><div className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar participante…"/><kbd>⌘ K</kbd></div><button className="icon-btn" onClick={()=>{setNotice('Recarregando o arquivo padrão…');loadDefault()}} title="Recarregar dados"><RefreshCw size={17}/></button></div></header>{notice&&<div className={`notice ${noticeType}`}><span>{noticeType==='error'?<AlertCircle size={16}/>:noticeType==='info'?<RefreshCw size={16}/>:<CheckCircle2 size={16}/>}</span>{notice}<button onClick={()=>setNotice('')}><X size={14}/></button></div>}
 {page==='dashboard'&&<Dashboard activities={activities} stats={stats} valid={valid} total={total} completion={completion} go={navigate}/>} 
 {page==='ranking'&&<Ranking stats={stats} select={s=>{setSel(s);setPage('participants')}}/>}
 {page==='duels'&&<Duels stats={stats}/>}
 {page==='participants'&&(sel?<Profile s={sel} back={()=>setSel(null)}/>:<Participants stats={filtered} select={setSel}/>)}
 {page==='evolution'&&<Evolution activities={activities} stats={stats}/>} 
 {page==='calendar'&&<Calendar activities={activities} stats={stats}/>} 
 {page==='curiosities'&&<Curiosities activities={activities} stats={stats}/>}
 {page==='import'&&<ImportPage members={members} activities={activities} importJSON={importJSON} unlocked={importUnlocked} onUnlock={requestImportAccess} onChooseFile={openFilePicker} reload={()=>{loadDefault();setNotice('Dados padrão recarregados.');setNoticeType('ok')}}/>}
 <input ref={fileInputRef} className="global-file-input" type="file" accept="application/json,.json" onChange={importJSON}/>
 {showPassword&&<PasswordModal value={password} setValue={setPassword} error={passwordError} onClose={()=>setShowPassword(false)} onConfirm={unlockImport}/>}
 </main></div>
}
const Card=({title,sub,children,action,className=''})=><section className={`card ${className}`}><div className="card-head"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{action}</div>{children}</section>;
const Stat=({I,t,v,delta})=><div className="stat"><div className="stat-icon"><I size={19}/></div><div className="stat-copy"><span>{t}</span><strong>{v}</strong>{delta&&<small><ArrowUpRight size={12}/>{delta}</small>}</div></div>;
const Avatar=({s,size=''})=>s?.m?.profile_picture_url?<img alt="" className={`avatar ${size}`} src={s.m.profile_picture_url}/>:<div className={`avatar ${size}`}>{s?.m?.full_name?.[0]||'?'}</div>;
const PersonSelect=({stats,value,onChange,label='Participante'})=><label className="select-wrap"><span>{label}</span><select value={value??''} onChange={e=>onChange(e.target.value===''?'':Number(e.target.value))}><option value="">Todos os participantes</option>{stats.map(s=><option key={s.m.id} value={s.m.id}>{s.m.full_name}</option>)}</select></label>;
function Dashboard({activities,stats,valid,total,completion,go}){const collectiveTarget=stats.length*challenge.target;const types=Object.entries(activities.reduce((o,a)=>(o[a.type]=(o[a.type]||0)+1,o),{})).sort((a,b)=>b[1]-a[1]).slice(0,6),max=Math.max(...types.map(x=>x[1]),1);const days=Array.from({length:14},(_,i)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-13+i);const key=isoDay(d);return{label:d.toLocaleDateString('pt-BR',{weekday:'short'}).slice(0,3),value:activities.filter(a=>a.date&&isoDay(new Date(a.date))===key).length}});const maxD=Math.max(...days.map(x=>x.value),1);return <><div className="hero"><div><div className="hero-label"><i/> AO VIVO</div><h2>O desafio está em movimento.</h2><p>Acompanhe desempenho, consistência e evolução da turma em um só lugar.</p></div><div className="hero-goal"><span>Progresso coletivo da meta</span><strong>{completion}%</strong><div><i style={{width:`${completion}%`}}/></div><small>{valid.length} válidos de {collectiveTarget} possíveis · {challenge.target} por participante</small></div></div><div className="stats"><Stat I={Users} t="Participantes" v={stats.length}/><Stat I={Activity} t="Check-ins registrados" v={activities.length}/><Stat I={Trophy} t="Check-ins válidos" v={valid.length}/><Stat I={AlertCircle} t="Abaixo de 30 min" v={activities.length-valid.length}/><Stat I={Clock3} t="Tempo em check-ins válidos" v={fmt(total)}/><Stat I={Target} t="Progresso da meta" v={`${completion}%`}/></div><div className="grid two"><Card title="Check-ins registrados por dia" sub="Últimos 14 dias · inclui válidos e abaixo do mínimo" action={<button className="ghost" onClick={()=>go('evolution')}>Ver evolução <ChevronRight size={14}/></button>}><div className="mini-chart">{days.map((x,i)=><div className="bar-col" key={i}><span>{x.value||''}</span><i><em style={{height:`${pct(x.value,maxD)}%`}}/></i><small>{x.label}</small></div>)}</div></Card><Card title="Ranking atual" sub="Check-ins válidos" action={<button className="ghost" onClick={()=>go('ranking')}>Ranking completo <ChevronRight size={14}/></button>}>{stats.slice(0,5).map((s,i)=><RankRow key={s.m.id} s={s} i={i}/>)}</Card></div><div className="grid two"><Card title="Check-ins por tipo" sub="Todos os registros importados"><div className="type-list">{types.map(([k,v])=><div className="type" key={k}><div><span>{k}</span><b>{v}</b></div><div className="line"><i style={{width:`${v/max*100}%`}}/></div></div>)}</div></Card><Card title="Últimos check-ins" sub="Registros mais recentes"><div className="activity-list">{activities.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,6).map(a=><div className="activity-item" key={a.id}><span>{shortDay(a.date)}</span><div><b>{a.name}</b><small>{a.type}</small></div><strong>{fmt(a.minutes)}</strong><i className={a.valid?'ok':'warn'}>{a.valid?'OK':'<30'}</i></div>)}</div></Card></div></>}
function RankRow({s,i}){return <div className="rank-row"><div className={`rank-num r${i+1}`}>{i+1}</div><Avatar s={s}/><div className="rank-name"><b>{s.m.full_name}</b><span>{s.days} dias ativos · sequência {s.streak}</span></div><strong>{s.v.length}</strong><small>check-ins</small></div>}
function Ranking({stats,select}){return <Card title="Ranking de performance" sub="Ordenado por check-ins válidos e tempo acumulado"><div className="table-head"><span>#</span><span>PARTICIPANTE</span><span>DIAS</span><span>SEQUÊNCIA</span><span>TEMPO</span><span>CHECK-INS</span></div>{stats.map((s,i)=><div className="ranking-row clickable" key={s.m.id} onClick={()=>select(s)}><div className={`rank-num r${i+1}`}>{i+1}</div><Avatar s={s}/><div><b>{s.m.full_name}</b><span>{pct(s.v.length,challenge.target)}% da meta</span></div><strong>{s.days}</strong><strong>{s.streak}</strong><strong>{fmt(s.time)}</strong><strong className="score">{s.v.length}</strong></div>)}</Card>}
function Duels({stats}){
 const[aId,setAId]=useState('');
 const[bId,setBId]=useState('');
 const a=stats.find(s=>String(s.m.id)===String(aId));
 const b=stats.find(s=>String(s.m.id)===String(bId));
 const rows=a&&b?[
  ['Check-ins válidos',a.v.length,b.v.length,'count'],
  ['Tempo acumulado',a.time,b.time,'time'],
  ['Dias ativos',a.days,b.days,'count'],
  ['Maior sequência',a.streak,b.streak,'count'],
  ['Média por treino',a.avg,b.avg,'time'],
  ['Calorias',a.calories,b.calories,'calories'],
  ['Passos',a.steps,b.steps,'steps'],
  ['Distância',a.distance,b.distance,'distance']
 ]:[];
 const format=(v,type)=>type==='time'?fmt(v):type==='calories'?`${Math.round(v||0).toLocaleString('pt-BR')} kcal`:type==='steps'?`${Math.round(v||0).toLocaleString('pt-BR')} passos`:type==='distance'?`${(v||0).toLocaleString('pt-BR',{maximumFractionDigits:1})} mi`:String(v||0);
 const winner=(x,y,type)=>{if(x===y)return 'tie';return x>y?'a':'b'};
 const scoreA=rows.filter(r=>winner(r[1],r[2],r[3])==='a').length;
 const scoreB=rows.filter(r=>winner(r[1],r[2],r[3])==='b').length;
 return <><div className="duel-hero"><div><span className="eyebrow">HEAD TO HEAD</span><h2>Escolha dois participantes e coloque os números frente a frente.</h2><p>Uma comparação direta de performance durante o desafio.</p></div><div className="duel-icon"><Swords size={30}/></div></div><div className="duel-selectors"><PersonSelect stats={stats} value={aId} onChange={v=>setAId(v)} label="Competidor 1"/><div className="versus">VS</div><PersonSelect stats={stats.filter(s=>String(s.m.id)!==String(aId))} value={bId} onChange={v=>setBId(v)} label="Competidor 2"/></div>{a&&b?<><div className="duel-score"><div><Avatar s={a} size="lg"/><strong>{a.m.full_name}</strong><b>{scoreA}</b><span>vantagens</span></div><div className="duel-vs">VS</div><div><Avatar s={b} size="lg"/><strong>{b.m.full_name}</strong><b>{scoreB}</b><span>vantagens</span></div></div><Card title="Comparação de performance" sub="Quem tiver o maior valor vence o indicador"><div className="duel-table">{rows.map(([label,av,bv,type])=>{const w=winner(av,bv,type);return <div className="duel-row" key={label}><div><span>{label}</span><strong className={w==='a'?'winner':''}>{format(av,type)}</strong></div><em>{w==='tie'?'EMPATE':w==='a'?a.m.full_name:b.m.full_name}</em><div><strong className={w==='b'?'winner':''}>{format(bv,type)}</strong></div></div>})}</div></Card></>:<Card title="Monte seu duelo" sub="Selecione dois participantes acima para começar"><div className="duel-empty"><Swords size={28}/><strong>Escolha dois participantes</strong><span>O duelo compara check-ins, tempo, dias ativos, sequência, média, calorias, passos e distância.</span></div></Card>}</>}
function Participants({stats,select}){return <Card title="Participantes" sub="Clique em um perfil para ver os detalhes"><div className="people">{stats.map((s,i)=><button key={s.m.id} onClick={()=>select(s)}><div className="person-top"><Avatar s={s} size="lg"/><span className="position">#{i+1}</span></div><strong>{s.m.full_name}</strong><span>{s.v.length} check-ins · {fmt(s.time)}</span><div className="person-progress"><i style={{width:`${pct(s.v.length,challenge.target)}%`}}/></div><small>{pct(s.v.length,challenge.target)}% da meta</small></button>)}</div></Card>}
function Profile({s,back}){return <><button className="back" onClick={back}>← Voltar para participantes</button><div className="profile-head"><Avatar s={s} size="xl"/><div><span className="eyebrow">PERFIL DE PERFORMANCE</span><h2>{s.m.full_name}</h2><p>Posição atual no ranking: <b>#{s.rank}</b></p></div><div className="profile-badge"><Medal size={17}/> {pct(s.v.length,challenge.target)}% da meta</div></div><div className="stats"><Stat I={Activity} t="Check-ins válidos" v={s.v.length}/><Stat I={Clock3} t="Tempo total" v={fmt(s.time)}/><Stat I={CalendarDays} t="Dias ativos" v={s.days}/><Stat I={Flame} t="Maior sequência" v={`${s.streak} dias`}/><Stat I={Timer} t="Média por treino" v={fmt(s.avg)}/></div><Card title="Histórico de atividades" sub="Todos os registros deste participante"><div className="table-head history"><span>DATA</span><span>ATIVIDADE</span><span>DURAÇÃO</span><span>STATUS</span></div>{s.a.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)).map(a=><div className="history-row" key={a.id}><span>{day(a.date)}</span><b>{a.type}</b><strong>{fmt(a.minutes)}</strong><span className={a.valid?'status-ok':'status-warn'}>{a.valid?'Check-in válido':'Abaixo de 30 min'}</span></div>)}</Card></>}
function Evolution({activities,stats}){const[person,setPerson]=useState('');const selected=person===''?null:stats.find(s=>s.m.id===person);const source=selected?selected.v:activities.filter(a=>a.valid);const weeks=Array.from({length:7},(_,i)=>{const start=new Date(`${challenge.start}T12:00:00`);start.setDate(start.getDate()+i*7);const end=new Date(start);end.setDate(end.getDate()+6);const v=source.filter(a=>{const d=new Date(a.date);return d>=start&&d<new Date(end.getTime()+86400000)});return{n:i+1,count:v.length,time:v.reduce((s,a)=>s+a.minutes,0)}});const max=Math.max(...weeks.map(w=>w.count),1);const total=weeks.reduce((s,w)=>s+w.count,0);return <><div className="section-toolbar"><div><span className="eyebrow">ANÁLISE POR PESSOA</span><h2>{selected?selected.m.full_name:'Evolução da turma'}</h2><p>{selected?'Compare as 7 semanas deste participante.':'Selecione uma pessoa para uma leitura individual.'}</p></div><PersonSelect stats={stats} value={person} onChange={setPerson}/></div><div className="stats"><Stat I={Activity} t="Check-ins" v={total}/><Stat I={Clock3} t="Tempo" v={fmt(weeks.reduce((s,w)=>s+w.time,0))}/><Stat I={TrendingUp} t="Melhor semana" v={`Sem. ${weeks.slice().sort((a,b)=>b.count-a.count)[0].n}`}/><Stat I={Flame} t="Sequência" v={`${selected?.streak||Math.max(...stats.map(s=>s.streak),0)} dias`}/></div><Card title="Evolução semanal" sub={selected?'Check-ins válidos por semana para o participante selecionado.':'Visão consolidada da turma. Selecione uma pessoa acima para detalhar.'}><div className="big-chart">{weeks.map(w=><div className="big-bar" key={w.n}><div className="bar-value">{w.count}</div><i><em style={{height:`${pct(w.count,max)}%`}}/></i><b>SEM {w.n}</b><small>{fmt(w.time)}</small></div>)}</div></Card>{selected&&<Card title="Resumo semanal" sub="Tempo e quantidade de check-ins"><div className="week-grid">{weeks.map(w=><div key={w.n}><b>Semana {w.n}</b><strong>{w.count}</strong><span>check-ins</span><small>{fmt(w.time)}</small></div>)}</div></Card>}</>}
function Calendar({activities,stats}){const[person,setPerson]=useState('');const selected=person===''?null:stats.find(s=>s.m.id===person);const source=selected?selected.a:activities;const s=new Date(`${challenge.start}T12:00:00`);return <><div className="section-toolbar"><div><span className="eyebrow">VISÃO DIÁRIA</span><h2>{selected?`Calendário de ${selected.m.full_name}`:'Calendário do desafio'}</h2><p>{selected?'Cada quadrado mostra o status diário desta pessoa.':'Escolha um participante para acompanhar a consistência individual.'}</p></div><PersonSelect stats={stats} value={person} onChange={setPerson}/></div><Card title={selected?'Calendário individual':'Calendário geral'} sub="49 dias · 7 semanas"><div className="calendar-legend"><span><i className="valid"/> atividade válida</span><span><i className="warn-dot"/> abaixo de 30 min</span><span><i className="empty"/> sem registro</span></div><div className="calendar">{Array.from({length:49},(_,i)=>{const d=new Date(s);d.setDate(d.getDate()+i);const iso=isoDay(d);const list=source.filter(a=>a.date&&isoDay(new Date(a.date))===iso);const valid=list.filter(a=>a.valid).length;const hasInvalid=list.length&&!valid;return <div className={`${valid?'has':''} ${hasInvalid?'warn':''}`} key={iso} title={`${d.toLocaleDateString('pt-BR')}: ${valid} válido(s), ${list.length-valid} abaixo do mínimo`}><small>Dia {i+1}</small><b>{d.getDate()}</b>{valid>1&&<em>{valid}</em>}{list.length>0&&<span className="calendar-dot"/>}</div>})}</div></Card></>}
function Curiosities({activities,stats}){
 const valid=activities.filter(a=>a.valid);
 const longest=valid.reduce((a,b)=>!a||b.minutes>a.minutes?b:a,null);
 const popular=Object.entries(valid.reduce((o,a)=>(o[a.type]=(o[a.type]||0)+1,o),{})).sort((a,b)=>b[1]-a[1])[0];
 const bestStreak=stats.slice().sort((a,b)=>b.streak-a.streak)[0];
 const bestTime=stats.slice().sort((a,b)=>b.time-a.time)[0];
 const bestCalories=stats.filter(s=>s.calories>0).sort((a,b)=>b.calories-a.calories)[0];
 const bestSteps=stats.filter(s=>s.steps>0).sort((a,b)=>b.steps-a.steps)[0];
 const bestAvg=stats.filter(s=>s.avg>0).sort((a,b)=>b.avg-a.avg)[0];
 const bestDays=stats.slice().sort((a,b)=>b.days-a.days||b.v.length-a.v.length)[0];
 const daily=Object.entries(valid.reduce((o,a)=>{const k=day(a.date);o[k]=(o[k]||0)+1;return o},{})).sort((a,b)=>b[1]-a[1])[0];
 const dailyTime=Object.entries(valid.reduce((o,a)=>{const k=day(a.date);o[k]=(o[k]||0)+a.minutes;return o},{})).sort((a,b)=>b[1]-a[1])[0];
 const dailyMax=Object.entries(valid.reduce((o,a)=>{const k=day(a.date);o[k]=(o[k]||0)+1;return o},{})).sort((a,b)=>b[1]-a[1])[0];
 const bestDistance=stats.filter(s=>s.distance>0).sort((a,b)=>b.distance-a.distance)[0];
 const activityDayCounts=Object.values(valid.reduce((o,a)=>{
   const d=day(a.date);
   const k=`${a.participantId}|${d}`;
   if(!o[k]) o[k]={participantId:a.participantId,date:d,count:0,types:[]};
   o[k].count+=1;
   if(a.type&&!o[k].types.includes(a.type)) o[k].types.push(a.type);
   return o;
 },{}));
 // A curiosidade considera quem registrou mais de uma atividade no mesmo dia.
 // O desempate prioriza mais tipos diferentes de atividade e depois a data mais antiga.
 const multiActivityDays=activityDayCounts.filter(x=>x.count>1);
 const mostInOneDay=multiActivityDays.sort((a,b)=>b.count-a.count||b.types.length-a.types.length||a.date.localeCompare(b.date)||String(a.participantId).localeCompare(String(b.participantId)))[0];
 const mostInOneDayPerson=mostInOneDay?stats.find(s=>String(s.m.id)===String(mostInOneDay.participantId)):null;
 const mostInOneDayTypes=mostInOneDay?.types?.map(t=>labels[t]||t.replace(/_/g,' ')).join(' + ');
 const earliest=valid.slice().sort((a,b)=>new Date(a.date)-new Date(b.date))[0];
 const latest=valid.slice().sort((a,b)=>new Date(b.date)-new Date(a.date))[0];
 return <><div className="curios-grid">
 <Insight icon="🏆" title="Mais check-ins" name={stats[0]?.m.full_name} value={`${stats[0]?.v.length||0} válidos`} tone="gold"/>
 <Insight icon="⏱️" title="Maior tempo acumulado" name={bestTime?.m.full_name} value={fmt(bestTime?.time||0)} tone="blue"/>
 <Insight icon="🔥" title="Maior sequência" name={bestStreak?.m.full_name} value={`${bestStreak?.streak||0} dias consecutivos`} tone="orange"/>
 <Insight icon="💪" title="Atividade mais comum" name={popular?.[0]} value={`${popular?.[1]||0} registros`} tone="green"/>
 <Insight icon="⚡" title="Treino mais longo" name={longest?.name} value={`${longest?.type||'—'} · ${fmt(longest?.minutes||0)}`} tone="purple"/>
 <Insight icon="🔥" title="Maior gasto calórico" name={bestCalories?.m.full_name} value={bestCalories?`${Math.round(bestCalories.calories).toLocaleString('pt-BR')} kcal`:'Sem dados de calorias'} tone="orange"/>
 <Insight icon="👟" title="Maior quantidade de passos" name={bestSteps?.m.full_name} value={bestSteps?`${Math.round(bestSteps.steps).toLocaleString('pt-BR')} passos`:'Sem dados de passos'} tone="blue"/>
 <Insight icon="📊" title="Maior média por treino" name={bestAvg?.m.full_name} value={bestAvg?fmt(bestAvg.avg):'Sem dados'} tone="green"/>
 <Insight icon="📅" title="Mais dias ativos" name={bestDays?.m.full_name} value={`${bestDays?.days||0} dias`} tone="gold"/>
 <Insight icon="📈" title="Dia mais movimentado" name={daily?.[0]||'Sem dados'} value={`${daily?.[1]||0} check-ins`} tone="purple"/>
 <Insight icon="⏳" title="Dia com mais tempo treinado" name={dailyTime?.[0]||'Sem dados'} value={dailyTime?fmt(dailyTime[1]):'Sem dados'} tone="blue"/>
 <Insight icon="🏃" title="Maior distância acumulada" name={bestDistance?.m.full_name} value={bestDistance?`${bestDistance.distance.toLocaleString('pt-BR',{maximumFractionDigits:1})} mi`:'Sem dados de distância'} tone="green"/>
 <Insight icon="🔁" title="Mais atividades em um dia" name={mostInOneDayPerson?.m.full_name} value={mostInOneDay?`${mostInOneDay.count} atividades · ${mostInOneDay.date}${mostInOneDayTypes?` · ${mostInOneDayTypes}`:''}`:'Nenhum dia com mais de uma atividade'} tone="orange"/>
 <Insight icon="🦍" title="Primeiro check-in do desafio" name={earliest?.name} value={earliest?`${day(earliest.date)} · ${fmt(earliest.minutes)}`:'Sem dados'} tone="red"/>
 <Insight icon="🏁" title="Check-in válido mais recente" name={latest?.name} value={latest?`${day(latest.date)} · ${fmt(latest.minutes)}`:'Sem dados'} tone="purple"/>
 </div><div className="curiosity-note">Os indicadores de calorias, passos e distância dependem dos dados enviados pelo export do Gym Rats. Quando o campo não estiver disponível, o sistema não estima o valor.</div></>
}
function Insight({icon,title,name,value,tone}){return <div className={`insight ${tone}`}><div className="insight-icon">{icon}</div><span>{title}</span><h3>{name||'Dados insuficientes'}</h3><b>{value}</b></div>}
function PasswordModal({value,setValue,error,onClose,onConfirm}){const[show,setShow]=useState(false);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="password-modal"><div className="password-icon"><LockKeyhole size={24}/></div><span className="eyebrow">ÁREA RESTRITA</span><h2>Autorizar importação</h2><p>Informe a senha para carregar uma nova base de dados do Gym Rats.</p><div className="password-field"><input autoFocus type={show?'text':'password'} value={value} placeholder="Digite a senha" onChange={e=>setValue(e.target.value)} onKeyDown={e=>e.key==='Enter'&&onConfirm()}/><button type="button" onClick={()=>setShow(!show)} aria-label="Mostrar senha">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div>{error&&<div className="password-error"><AlertCircle size={15}/>{error}</div>}<div className="modal-actions"><button className="ghost-btn" onClick={onClose}>Cancelar</button><button className="primary-btn" onClick={onConfirm}><LockKeyhole size={15}/> Autorizar</button></div><small className="security-note">A importação substitui os dados atualmente carregados.</small></div></div>}
function ImportPage({members,activities,importJSON,reload,unlocked,onUnlock,onChooseFile}){return <div className="import-page"><div className="import-hero"><div className="import-icon"><FileJson/></div><div><span className="eyebrow">CENTRAL DE DADOS</span><h2>Importe o export do Gym Rats</h2><p>O sistema lê o JSON, normaliza participantes e check-ins e atualiza todos os painéis automaticamente.</p></div><div className={`access-badge ${unlocked?'open':'locked'}`}>{unlocked?<><CheckCircle2 size={15}/> Importação autorizada</>:<><LockKeyhole size={15}/> Importação protegida</>}</div></div><div className="grid two"><Card title="Importar arquivo" sub="Formato aceito: JSON"><button type="button" className={`dropzone ${!unlocked?'protected':''}`} onClick={unlocked?onChooseFile:onUnlock}><div className="dropzone-icon">{unlocked?<Upload size={28}/>:<LockKeyhole size={28}/>}</div><strong>{unlocked?'Selecionar arquivo challenge-data.json':'Importação protegida por senha'}</strong><span>{unlocked?'Clique para escolher o arquivo. Após selecionar, ele será validado antes de substituir os dados atuais.':'Clique aqui para informar a senha e liberar a importação.'}</span></button><div className="import-actions"><button className="primary-btn" onClick={unlocked?onChooseFile:onUnlock}>{unlocked?<><Upload size={15}/> Selecionar arquivo</>:<><LockKeyhole size={15}/> Informar senha</>}</button><button className="ghost-btn" onClick={reload}><RefreshCw size={15}/> Recarregar dados padrão</button></div></Card><Card title="Dados carregados" sub="Resumo da base atual"><div className="import-kpis"><div><strong>{members.length}</strong><span>participantes</span></div><div><strong>{activities.length}</strong><span>check-ins</span></div><div><strong>{activities.filter(a=>a.valid).length}</strong><span>válidos</span></div></div><div className="import-tip"><CheckCircle2 size={17}/><span>Depois da importação, Ranking, Evolução, Calendário e Curiosidades são recalculados automaticamente.</span></div></Card></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
